source "https://rubygems.org"

group :jekyll_plugins do
  gem "github-pages", "= 228"
  gem "jekyll-tabs", '~> 1.1'
end

# Work around https://github.com/jekyll/jekyll/issues/8523
gem "webrick", "~> 1.7"
